version: '2'
services:
  nginx:
    build: docker/dev-nginx/
    image: debiki/ed-nginx
    command: nginx
    volumes:
      - ./docker/data/uploads/:/opt/ed/uploads/:ro
      - ./docker/data/letsencrypt/:/etc/letsencrypt/:ro
    ports:
      # Don't expose port 81 (for publishing WebSocket events)  — it should be reachable only
      # from inside the Docker network.
      - '80:80'
      - '443:443'
    depends_on:
      - play

  play:
    build: docker/dev-play/
    # image debiki/ed-play instead built & tagged in docker/build-play-prod.sh.
    stdin_open: true  # otherwise Play exits
    volumes:
      - ./:/opt/ed/server/
      # Without this it takes forever to start because sbt would always download all dependencies.
      - ~/.ivy2/:/home/owner/.ivy2/
      - ~/.sbt/:/home/owner/.sbt/
    ports:
      - '9000:9000' # Play's HTTP listen port.
      - '9999:9999' # Java debugger port
      - '3333:3333' # JMX
    links:
      - postgres
      - redis
    environment:
      PLAY_HEAP_MEMORY_MB: 1048

  redis:
    image: redis:3.0.7-alpine
    volumes:
      - ./docker/data/redis/:/data/
    ports:
      - '6379:6379'

  postgres:
    build: docker/postgres/
    image: debiki/ed-postgres
    volumes:
      - ./docker/data/postgres/:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'public'
      PEER_HOST: 'postgres2'
      PEER_PORT: '5432'
      PEER_PASSWORD: 'public2'

  # An extra database, so you can experiment with Postgres replication and failover.
  # You don't need to start it.
  postgres2:
    build: docker/postgres/
    volumes:
      - ./docker/data/postgres2/:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 'public2'
      PEER_HOST: 'postgres'
      PEER_PORT: '5432'
      PEER_PASSWORD: 'public'

  gulp:
    build: docker/dev-gulp/
    volumes:
      - ./:/opt/debiki/server/

# vim: et ts=2 sw=2
