version: '2'
services:
  nginx:
    build: docker/dev-nginx/
    image: debiki/ed-nginx
    command: nginx
    volumes:
      - ../uploads/:/opt/debiki/uploads/:ro
      - ../letsencrypt/:/etc/letsencrypt/:ro
    ports:
      # Don't expose port 81 (for publishing WebSocket events)  — it should be reachable only
      # from inside the Docker network.
      - '80:80'
      - '443:443'
    depends_on:
      - play

  play:
    build: docker/dev-play/
    # image debiki/ed-play instead built & tagged in docker/build-play-prod.sh.
    stdin_open: true  # otherwise Play exits
    volumes:
      - ../:/opt/debiki/
      # Without this it takes forever to start because sbt would always download all dependencies.
      - ~/.ivy2/:/home/owner/.ivy2/
      - ~/.sbt/:/home/owner/.sbt/
    ports:
      - '9000:9000' # Play's HTTP listen port.
      - '9999:9999' # Java debugger port
      - '3333:3333' # JMX
    links:
      - db:database
      - redis
    environment:
      PLAY_MEM_MB: 1048

  redis:
    image: redis:3.0.7-alpine
    volumes:
      - ../redis/:/data/
    ports:
      - '6379:6379'

  db:
    build: docker/postgres/
    image: debiki/ed-postgres
    volumes:
      - ../db/:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'public-69KF24KYU53XW2'
      PEER_HOST: 'db2'
      PEER_PORT: '5432'
      PEER_PASSWORD: 'public-24KPY0594YKF'

  # An extra database, so you can experiment with Postgres replication and failover.
  # You don't need to start it.
  db2:
    build: docker/postgres/
    volumes:
      - ../db2/:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 'public-24KPY0594YKF'
      PEER_HOST: 'db'
      PEER_PORT: '5432'
      PEER_PASSWORD: 'public-69KF24KYU53XW2'

  gulp:
    build: docker/dev-gulp/
    volumes:
      - ../:/opt/debiki/

# vim: et ts=2 sw=2
