version: '2'
services:
  nginx:
    build: docker/dev-nginx/
    command: nginx
    volumes:
      - ../uploads/:/opt/debiki/uploads/:ro
      - ../letsencrypt/:/etc/letsencrypt/:ro
    ports:
      - '80:80'
      - '443:443'
      # Don't expose port 81 (for publishing WebSocket events)  — it should be reachable only
      # from inside the Docker network.
    depends_on:
      - play

  play:
    build: docker/dev-play/
    stdin_open: true  # otherwise Play exits
    volumes:
      - ../:/opt/debiki/
      # Without this it takes forever to start because sbt would always download all dependencies.
      - ~/.ivy2/:/home/owner/.ivy2/
      - ~/.sbt/:/home/owner/.sbt/
    ports:
      - '9000:9000' # Play's HTTP listen port.
      - '9999:9999' # Java debugger port
      - '3333:3333' # JMX
    links:
      - db:database
      - redis
    environment:
      PLAY_MEM_MB: 1048

  redis:
    image: redis:3.0.7-alpine
    ports:
      - '6379:6379'

  db:
    image: postgres:9.5.2
    ports:
      - '5432:5432'

  gulp:
    build: docker/dev-gulp/
    volumes:
      - ../:/opt/debiki/

# vim: et ts=2 sw=2
