# These rules make Traefik send requests to the web container,
# without generating any custom certificate, by default. That's good for
# any  *.wildcard-domain.com of yours (you're supposed to provide your
# own certificate).
#
# Play Framework in the app container keeps up-to-date another file with
# frontends and Host rules for custom hostnames, so they'll get their own
# onHostRule generated cert. [ATOGTRFK]


# Instead of `PathPrefix:/` below, could also use:
#  `HostRegexp: {subdomain:[a-z]+}.main.domain.com`,
# however that's more complicated, and wouldn't work with ip addresses, in case
# one wants to access one's site, before there's a hostname pointing to it?
[frontends.talkyard_default]
  entryPoints = ["http", "https"]
  backend = "talkyard_web"
  passHostHeader = true
  priority = 1
  [frontends.talkyard_default.routes.rule_1]
    # Send all traffic that's not handled by a Host: specific rule, to here, e.g.
    # any main wildcard domain.
    rule = "PathPrefix:/"


# This could maybe instead be a Docker provider backend, declared in the
# docker-compose.yml file, but Traefik doesn't support using more than one
# provider.  [5BSRQ01]
[backends]
  [backends.talkyard_web]
    [backends.talkyard_web.servers]
      [backends.talkyard_web.servers.server_1]
        url = "http://web:80"
        weight = 1

