
[frontends]
  [frontends.talkyard_wildcard]
    entryPoints = ["http", "https"]
    backend = "talkyard_web"
    passHostHeader = true
    priority = 1  # lowest

    [frontends.talkyard_frontend.routes.rule_1]
      rule = "PathPrefix:/"

  
    [frontends.talkyard_frontend.errors]
    [frontends.talkyard_frontend.errors.network]
      status = ["502"]
      backend = "error"
      query = "/{status}.html"