name: debiki_admin
version: 0.0.1
dependencies:
  angular: any
  browser: any
  js: any
  shadow_dom: any
  angular_ui:
    path: ../../../modules/angular.dart.ui-kajmagnus79

dev_dependencies:
  unittest: any
